# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyIgniteProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyIgniteProject
  pod 'AppCenter/Push', '~> 1.1.0'
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'MyIgniteProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MyIgniteProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyIgniteProject-tvOS

  target 'MyIgniteProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
